# Generated by Django 5.2.16 on 2026-08-05 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0003_alter_case_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('species', models.CharField(max_length=50)),
                ('breed', models.CharField(blank=True, default='Unknown', max_length=100)),
                ('estimated_age', models.CharField(blank=True, default='', max_length=50)),
                ('distinguishing_features', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='animal_photos/')),
                ('temperament_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('adoption_status', models.CharField(choices=[('Not_Available', 'Not Available'), ('Available', 'Available'), ('Adoption_Pending', 'Adoption Pending'), ('Adopted', 'Adopted'), ('Fostered', 'Fostered')], default='Not_Available', max_length=20)),
                ('ownership_status', models.CharField(choices=[('Stray', 'Stray'), ('Abandoned', 'Abandoned'), ('Owned', 'Owned'), ('Unknown', 'Unknown')], default='Unknown', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal', to='cases.case')),
                ('current_foster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fostered_animals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'animals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemperamentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperament_ratings', to='animals.animal')),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temperament_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'temperament_ratings',
            },
        ),
    ]
