# Generated by Django 5.2.16 on 2026-08-11 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotspotRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('run_date', models.DateField(auto_now_add=True)),
                ('eps_m', models.DecimalField(decimal_places=1, default=500.0, max_digits=6)),
                ('min_samples', models.SmallIntegerField(default=5)),
                ('total_cases_processed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hotspot_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HotspotCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_label', models.SmallIntegerField()),
                ('centroid_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('centroid_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('case_count', models.IntegerField(default=0)),
                ('dominant_species', models.CharField(blank=True, default='', max_length=50)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='analytics.hotspotrun')),
            ],
            options={
                'db_table': 'hotspot_clusters',
            },
        ),
    ]
