# Generated by Django 5.2.16 on 2026-07-24 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('ward_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('city', models.CharField(default='Bengaluru', max_length=100)),
                ('centroid_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('centroid_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'wards',
            },
        ),
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'animal_types',
                'unique_together': {('species', 'breed')},
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('species', models.CharField(max_length=50)),
                ('breed', models.CharField(blank=True, default='Unknown', max_length=100)),
                ('estimated_age', models.CharField(choices=[('Puppy', 'Puppy'), ('Kitten', 'Kitten'), ('Calf', 'Calf'), ('Juvenile', 'Juvenile'), ('Adult', 'Adult'), ('Senior', 'Senior')], default='Adult', max_length=20)),
                ('severity', models.SmallIntegerField(default=1)),
                ('aggression_level', models.SmallIntegerField(default=1)),
                ('injury_type', models.CharField(blank=True, default='', max_length=200)),
                ('bystander_action', models.CharField(choices=[('none', 'None'), ('fed', 'Fed'), ('contacted_ngo', 'Contacted NGO')], default='none', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('photo_url', models.URLField(blank=True, default='', max_length=500)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='case_photos/')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In_Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Escalated', 'Escalated'), ('Unresolved', 'Unresolved')], default='Open', max_length=20)),
                ('response_time_min', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_cases', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_cases', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(blank=True, db_column='ward_name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.ward')),
            ],
            options={
                'db_table': 'cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('is_auto_release', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_actions', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='cases.case')),
            ],
            options={
                'db_table': 'case_status_logs',
                'ordering': ['changed_at'],
            },
        ),
    ]
