# Generated by Django 5.2.16 on 2026-08-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_case_latitude_alter_case_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In_Progress', 'In Progress'), ('On_Site', 'On Site'), ('Resolved', 'Resolved'), ('Escalated', 'Escalated'), ('Unresolved', 'Unresolved')], default='Open', max_length=20),
        ),
    ]
