# Generated by Django 5.2.16 on 2026-08-13 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
        ('cases', '0003_alter_case_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundPetReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found_report_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('species', models.CharField(max_length=50)),
                ('breed', models.CharField(blank=True, default='Unknown', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='found_photos/')),
                ('found_location', models.CharField(max_length=200)),
                ('found_date', models.DateField()),
                ('ownership_signs', models.TextField(blank=True, default='')),
                ('current_custody', models.CharField(blank=True, default='', max_length=200)),
                ('distinguishing_features', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Matched', 'Matched'), ('Closed', 'Closed')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='found_reports', to='animals.animal')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'found_pet_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LostPetReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lost_report_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('pet_name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=50)),
                ('breed', models.CharField(blank=True, default='Unknown', max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='lost_photos/')),
                ('last_seen_location', models.CharField(max_length=200)),
                ('last_seen_date', models.DateField()),
                ('distinguishing_features', models.TextField(blank=True, default='')),
                ('collar_tag', models.CharField(blank=True, default='', max_length=100)),
                ('microchip_id', models.CharField(blank=True, default='', max_length=100)),
                ('reward', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Matched', 'Matched'), ('Closed', 'Closed')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lost_pet_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
