# Generated by Django 5.2.16 on 2026-08-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_casenotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='estimated_age',
            field=models.CharField(blank=True, default='Unknown', max_length=50),
        ),
    ]
