# Generated by Django 5.2.16 on 2026-08-14 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerReliabilityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrs_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('score_date', models.DateField()),
                ('cases_notified', models.SmallIntegerField(default=0)),
                ('cases_responded', models.SmallIntegerField(default=0)),
                ('cases_completed', models.SmallIntegerField(default=0)),
                ('avg_response_time_min', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('response_rate', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('completion_rate', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('vrs_score', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('flag_for_review', models.BooleanField(default=False)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vrs_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'volunteer_reliability_scores',
                'ordering': ['-score_date'],
                'unique_together': {('volunteer', 'score_date')},
            },
        ),
    ]
