# Generated by Django 5.2.16 on 2026-08-11 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Withdrawn', 'Withdrawn')], default='Active', max_length=20)),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_listing', to='animals.animal')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'adoption_listings',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='AdoptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adoption_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('welfare_survey_30d_sent', models.BooleanField(default=False)),
                ('welfare_survey_90d_sent', models.BooleanField(default=False)),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoptions', to=settings.AUTH_USER_MODEL)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_record', to='adoption.adoptionlisting')),
            ],
            options={
                'db_table': 'adoption_records',
            },
        ),
        migrations.CreateModel(
            name='AdopterInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_readiness_complete', models.BooleanField(default=False)),
                ('expressed_at', models.DateTimeField(auto_now_add=True)),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_interests', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='adoption.adoptionlisting')),
            ],
            options={
                'db_table': 'adopter_interests',
                'ordering': ['expressed_at'],
                'unique_together': {('listing', 'adopter')},
            },
        ),
    ]
